# -*- coding: utf-8 -*-
"""Regressão_linar_e_minimos_Quadrados_ordinarios.ipynb
O código é inspirado/cópia deste tutorial https://www.youtube.com/watch?v=w2RJ1D6kz-o&index=4&list=PL-Ogd76BhmcCO4VeOlIH93BMT5A_kKAXp
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPauyE8KtnsrnMNecRU4k_7Lk1sjSbdW
"""

import numpy as np

import matplotlib.pyplot as plt

from sklearn.datasets import load_boston

#Carregamos as bibliotecas
boston = load_boston()
print(boston.DESCR)

"""Formula do mínimo erro quadrático médio (MCO)  : $\beta = (X^{T}X)^{-1}$"""

#criando as matrizes
X = np.array(boston.data[:, 5])
Y = np.array(boston.target)

#colocando no gráfico a dispersão
plt.scatter(X, Y, alpha=0.3)



#nós adicionamos coluna de 1s para fins independentes

X=np.array([np.ones(506), X]).T


B = np. linalg.inv(X.T @ X ) @ X.T @ Y

plt.plot ([4, 9], [B[0] + B[1] * 4,  B[0] + B[1] * 9], c="red")
plt.show ()

B

